/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.GUI;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import java.time.LocalDate;

/**
 *
 * @author Gavin
 */
public class EditEntry extends javax.swing.JPanel {

  /**
   * Creates new form EditEntry
   */
  public EditEntry() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    improvementLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    improvementArea = new javax.swing.JTextArea();
    finishButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    gratefulLabel = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    gratefulArea = new javax.swing.JTextArea();

    improvementLabel.setText("How I Improved:");

    improvementArea.setColumns(20);
    improvementArea.setRows(5);
    jScrollPane1.setViewportView(improvementArea);

    finishButton.setText("Finish");
    finishButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        finishButtonActionPerformed(evt);
      }
    });

    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    gratefulLabel.setText("What I'm Grateful For:");

    gratefulArea.setColumns(20);
    gratefulArea.setRows(5);
    jScrollPane2.setViewportView(gratefulArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(96, 96, 96)
        .addComponent(cancelButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(finishButton)
        .addGap(95, 95, 95))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(315, 315, 315)
            .addComponent(improvementLabel))
          .addGroup(layout.createSequentialGroup()
            .addGap(275, 275, 275)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(299, 299, 299)
            .addComponent(gratefulLabel)))
        .addContainerGap(282, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(58, 58, 58)
        .addComponent(gratefulLabel)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
        .addComponent(improvementLabel)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(finishButton)
          .addComponent(cancelButton))
        .addGap(80, 80, 80))
    );
  }// </editor-fold>//GEN-END:initComponents
  /* Saves entry and returns to main card */
  private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
    // MAYBE SHOULD BE IN CONTROLLER
    
    LocalDate date = LocalDate.now();
    String saveLocation = Controller.Main.getSaveLocation() + date + ".txt";
    FileWriter fileWriter = new FileWriter(date + ".txt");
    BufferedWriter writer = new BufferedWriter(fileWriter);
    writer.write("Grateful:");
    writer.newLine();
    writer.write(getGratefulText());
    writer.write("Improvement:");
    writer.write(getImprovementText());
    writer.close();
    
    GUI.getInstance().goToCar(MainCard);
  }//GEN-LAST:event_finishButtonActionPerformed
  /* Returns to last card without saving entry */
  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    GUI.getInstance().goBack();
  }//GEN-LAST:event_cancelButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton finishButton;
  private javax.swing.JTextArea gratefulArea;
  private javax.swing.JLabel gratefulLabel;
  private javax.swing.JTextArea improvementArea;
  private javax.swing.JLabel improvementLabel;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  // End of variables declaration//GEN-END:variables
}
